# https://www.wilsonwilson.dev/articles/flutter-build-yaml/

targets:
  $default:
    builders:
      freezed|freezed:
        enabled: true
        generate_for:
          - "lib/core/models/app_exception.dart"
          - "lib/core/models/camera_state.dart"
